springdoc.swagger-ui.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/coopervote
spring.datasource.username=coopervote
spring.datasource.password=coopervote123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false