springdoc.swagger-ui.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/coopervote}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:coopervote}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:coopervote123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.db.enabled=true